turning_radius_measuring:

  actuator_values: [-1.0, -0.8, -0.6, -0.4, -0.2, 0.2, 0.4, 0.6, 0.8, 1.0]

  base_frame: "base_link"

  motor_during_turn: 0.15

  scan_window: 30
  range_change_threshold: 0.3

velocity_measuring:

  actuator_values: [0.15]

  measuring_distance: 2.0
  acceleration_distance: 1.0
