turning_radius_measuring:

  actuator_values: [-1.0, -0.8, -0.6, -0.4, -0.2, 0.2, 0.4, 0.6, 0.8, 1.0]

  base_frame: "base_link"

  velocity_actuator_value: 0.15

  filter_chain:
    - name: rotation_filter
      type: laser_filters/LaserScanRotationFilter
      params:
        index: 360
    - name: window_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.967 # -170째 TODO: figure this out!
        upper_angle: 2.967 # 170째 TODO: figure this out!
    - name: min_range_window_filter
      type: laser_filters/LaserScanMinRangeWindowFilter
      params:
        window_size: 180
        change_in_range_threshold: 0.3
        range_replacement_value: .inf
        intensity_replacement_value: .inf

velocity_measuring:

  actuator_values: [0.15]

  measuring_distance: 2.0
  acceleration_distance: 1.0
  safety_distance: 2.0

  filter_chain:
    - name: rotation_filter
      type: laser_filters/LaserScanRotationFilter
      params:
        index: 360
    - name: window_filter
        type: laser_filters/LaserScanAngularBoundsFilter
        params:
          lower_angle: -0.1745 # -10째
          upper_angle: 0.1745 # 10째
#    - name: array_filter
#        type: laser_filters/LaserArrayFilter
#        params:
#          range_filter_chain:
#            - name: range_median_filter
#              type: filters/MultiChannelMedianFilterFloat
#              params:
#                number_of_observations: 5
