# steering angle measuring params
# -------------------------------
steering_angle_measuring:
  base_frame: "base_link"

  servo_min: -1.0
  servo_max: 1.0
  servo_increment: 0.2

  motor_during_turn: 0.15

  scan_window: 30
  range_change_threshold: 0.3

# velocity measuring params
# -------------------------
velocity_measuring:
  motor_min: -0.3
  motor_max: 0.3
  motor_increment: 0.01

  measuring_distance: 2.0