turning_radius_measuring:
  scan_filter_chain:
    - name: window_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.57
        upper_angle: 1.57
    - name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.3
        upper_threshold: 0.4
        lower_replacement_value: -.inf
        upper_replacement_value: .inf

velocity_measuring:
  scan_filter_chain:
    - name: window_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -0.785 # -pi / 4
        upper_angle: 0.785 # pi / 4
    - type: laser_filters/LaserArrayFilter
      name: laser_median_filter
      params:
        range_filter_chain:
          - name: range_median_filter
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5