turning_radius_measuring_filter_chain:
  - name: window_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.57
      upper_angle: 1.57
  - name: range_filter
    type: laser_filters/LaserScanRangeFilter
    params:
      use_message_range_limits: false
      lower_threshold: 0.3
      upper_threshold: 0.4
      upper_replacement_value: .inf
      lower_replacement_value: -.inf

velocity_measuring_filter_chain:
  - name: window_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -0.785 # -pi / 4
      upper_angle: 0.785 # pi / 4
  - name: array_filter
    type: laser_filters/LaserArrayFilter
    params:
      range_filter_chain:
        - name: range_median_filter
          type: filters/MultiChannelMedianFilterFloat
          params:
            number_of_observations: 5
